name: Nightly builds

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  wezterm:
    name: Wezterm nightly builds
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install tools
        run: |
          dnf install -y --setopt=install_weak_deps=False -y createrepo_c git dnf-plugins-core findutils wget
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      - name: Get latest nightly
        run: |
          wget 'https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly-fedora35.rpm'
      - name: Check if updated
        id: check
        shell: bash
        run: |
          old=$(dnf repoquery --nevra --latest-limit 1 --repofrompath repo,repo/wezterm/fedora/35/x86_64/ --repo repo wezterm)
          new=$(rpm --qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}\n' -q wezterm-nightly-fedora35.rpm)
          echo "old: $old"
          echo "new: $new"
          if [ "$old" = "$new" ]; then
            echo '::set-output name=changed::false'
            rm wezterm-nightly-fedora35.rpm
          else
            echo '::set-output name=changed::true'
            mv wezterm-nightly-fedora35.rpm "repo/wezterm/fedora/35/x86_64/$new.rpm"
          fi
      - name: Rebuild RPM repository
        if: steps.check.outputs.changed
        run: |
          cd repo/wezterm/fedora/35/x86_64/
          ls -tp  | grep -v '/$' | tail -n +3 | xargs -d '\n' -r rm --
          rm -rf repodata
          rm -rf drpms
          createrepo . --zck
      - name: Publish to gh-pages
        if: steps.check.outputs.changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --amend --reset-author -m "latest generated wezterm repo"
          git push origin gh-pages --force-with-lease
