name: Nightly builds

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  wezterm:
    name: Wezterm nightly builds
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      - name: Get latest nightly
        run: |
          gh release download -R wez/wezterm nightly -p 'wezterm-nightly-fedora35.rpm'
      - name: Check if updated
        id: check
        shell: bash
        run: |
          old=$(dnf repoquery --repofrompath repo,repo/wezterm/fedora/35/x86_64/ --repo repo wezterm)
          old=${old/wezterm-0:/wezterm-}
          new=$(rpm -q wezterm-nightly-fedora35.rpm)
          if [ "$old" != "$new" ]; then
            echo '::set-output name=changed::true'
            mv wezterm-nightly-fedora35.rpm "repo/wezterm/fedora/35/x86_64/$new.rpm"
          else
            echo '::set-output name=changed::false'
          fi
      - name: Install tools
        if: steps.check.outputs.changed
        run: |
          dnf install --setopt=install_weak_deps=False -y createrepo_c git
      - name: Rebuild RPM repository
        if: steps.check.outputs.changed
        run: |
          ls -tp repo/wezterm/fedora/35/x86_64/ | grep -v '/$' | tail -n +4 | xargs -d '\n' -r rm --
          rm -rf repo/wezterm/fedora/35/x86_64/repodata
          rm -rf repo/wezterm/fedora/35/x86_64/drpms
          createrepo repo/wezterm/fedora/35/x86_64 --deltas --num-deltas 2 --zck
      - name: Publish to gh-pages
        if: steps.check.outputs.changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --amend --reset-author -m "latest generated wezterm repo"
          git push